-- Query 1: Top 10 Hospitals by Total Admissions
SELECT

    h.name AS hospital_name,

    COUNT(*) AS total_admissions

FROM admissions a

JOIN hospitals h
ON a.hospital_id = h.hospital_id

GROUP BY h.name

ORDER BY total_admissions DESC

LIMIT 10;

-- Query 2: Readmission Rate by Hospital
SELECT

    h.name AS hospital_name,

    ROUND(AVG(a.readmitted_30d) * 100, 2)
        AS readmission_rate

FROM admissions a

JOIN hospitals h
ON a.hospital_id = h.hospital_id

GROUP BY h.name

ORDER BY readmission_rate DESC;

-- Query 3: Average Length of Stay by Hospital
SELECT

    h.name,

    ROUND(AVG(a.los_days),2)
        AS average_los

FROM admissions a

JOIN hospitals h
ON a.hospital_id = h.hospital_id

GROUP BY h.name

ORDER BY average_los DESC;

-- Query 4: Total Revenue Generated by Hospital
SELECT

    h.name,

    ROUND(SUM(b.total_cost_inr),2)
        AS total_revenue

FROM admissions a

JOIN hospitals h
ON a.hospital_id = h.hospital_id

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY h.name

ORDER BY total_revenue DESC;

-- Query 5: Average Treatment Cost by Hospital Tier
SELECT

    h.tier,

    ROUND(AVG(b.total_cost_inr),2)
        AS average_cost

FROM admissions a

JOIN hospitals h
ON a.hospital_id = h.hospital_id

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY h.tier

ORDER BY average_cost DESC;

-- Query 6: Readmission Rate by Admission Type
SELECT

    admit_type,

    ROUND(AVG(readmitted_30d) * 100,2)
        AS readmission_rate

FROM admissions

GROUP BY admit_type

ORDER BY readmission_rate DESC;

-- Query 7: Readmission Rate by Ward Type
SELECT

    ward_type,

    ROUND(AVG(readmitted_30d) * 100,2)
        AS readmission_rate

FROM admissions

GROUP BY ward_type

ORDER BY readmission_rate DESC;

-- Query 8: Average Cost by Insurance Type
SELECT

    p.insurance_type,

    ROUND(AVG(b.total_cost_inr),2)
        AS average_cost

FROM admissions a

JOIN patients p
ON a.patient_id = p.patient_id

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY p.insurance_type

ORDER BY average_cost DESC;

-- Query 9: Revenue by Insurance Type
SELECT

    p.insurance_type,

    ROUND(SUM(b.total_cost_inr),2)
        AS total_revenue

FROM admissions a

JOIN patients p
ON a.patient_id = p.patient_id

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY p.insurance_type

ORDER BY total_revenue DESC;

-- Query 10: Average Cost by Cost Category
SELECT

    cost_category,

    ROUND(AVG(total_cost_inr),2)
        AS average_cost

FROM billing

GROUP BY cost_category

ORDER BY average_cost DESC;

-- Query 11: Top States by Admissions
SELECT

    p.state,

    COUNT(*) AS admissions

FROM admissions a

JOIN patients p
ON a.patient_id = p.patient_id

GROUP BY p.state

ORDER BY admissions DESC;

-- Query 12: Gender-wise Readmission Rate
SELECT

    p.gender,

    ROUND(AVG(a.readmitted_30d) * 100,2)
        AS readmission_rate

FROM admissions a

JOIN patients p
ON a.patient_id = p.patient_id

GROUP BY p.gender

ORDER BY readmission_rate DESC;

-- Query 13: Average Cost by Gender
SELECT

    p.gender,

    ROUND(AVG(b.total_cost_inr),2)
        AS average_cost

FROM admissions a

JOIN patients p
ON a.patient_id = p.patient_id

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY p.gender

ORDER BY average_cost DESC;

-- Query 14: Average Length of Stay by Gender
SELECT

    p.gender,

    ROUND(AVG(a.los_days),2)
        AS average_los

FROM admissions a

JOIN patients p
ON a.patient_id = p.patient_id

GROUP BY p.gender

ORDER BY average_los DESC;

-- Query 15: Top Diagnosis Categories
SELECT

    diag_category,

    COUNT(*) AS total_cases

FROM diagnoses

GROUP BY diag_category

ORDER BY total_cases DESC;

-- Query 16: Readmission Rate by Diagnosis Category
SELECT

    d.diag_category,

    ROUND(AVG(a.readmitted_30d) * 100,2)
        AS readmission_rate

FROM diagnoses d

JOIN admissions a
ON d.admission_id = a.admission_id

GROUP BY d.diag_category

ORDER BY readmission_rate DESC;

-- Query 17: Average Cost by Diagnosis Category
SELECT

    d.diag_category,

    ROUND(AVG(b.total_cost_inr),2)
        AS average_cost

FROM diagnoses d

JOIN billing b
ON d.admission_id = b.admission_id

GROUP BY d.diag_category

ORDER BY average_cost DESC;

-- Query 18: Top Hospitals by Average Cost
SELECT

    h.name,

    ROUND(AVG(b.total_cost_inr),2)
        AS average_cost

FROM admissions a

JOIN hospitals h
ON a.hospital_id = h.hospital_id

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY h.name

ORDER BY average_cost DESC

LIMIT 10;

-- Query 19: Monthly Admission Trend
SELECT

    strftime('%Y-%m', admit_date)
        AS month,

    COUNT(*) AS admissions

FROM admissions

GROUP BY month

ORDER BY month;

-- Query 20: Monthly Revenue Trend
SELECT

    strftime('%Y-%m', a.admit_date)
        AS month,

    ROUND(SUM(b.total_cost_inr),2)
        AS revenue

FROM admissions a

JOIN billing b
ON a.admission_id = b.admission_id

GROUP BY month

ORDER BY month;